<?php
$session = $this->session(); 
?>
<!doctype html>
<!--[if lt IE 7]> <html class="no-js lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title>NGPocket</title>  
  <meta name="description" content="">
  <meta name="author" content="revaxarts.com">
  <meta name="viewport" content="width=device-width,user-scalable=0">
    
    <!-- Apple iOS and Android stuff -->
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <link rel="apple-touch-icon-precomposed" href="img/icon.png">
    <link rel="apple-touch-startup-image" href="img/startup.png">
    <meta name="viewport" content="width=device-width,initial-scale=1,user-scalable=no,maximum-scale=1">
    
    <!-- Google Font and style definitions -->
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=PT+Sans:regular,bold">
    <link rel="stylesheet" href="/css/style.css">
    
    <!-- include the skins (change to dark if you like) -->
    <link rel="stylesheet" href="/css/light/theme.css" id="themestyle">
    <!-- <link rel="stylesheet" href="css/dark/theme.css" id="themestyle"> -->
    
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <link rel="stylesheet" href="css/ie.css">
    <![endif]-->
    
    <!-- Loading JS Files this way is not recommended! Merge them but keep their order -->
  <link href="http://fonts.googleapis.com/css?family=Ubuntu:400,700" rel="stylesheet" type="text/css">
  
</head>
<body>
        <div id="pageoptions">
            <ul>
                <li><a href="/index/logout"><?php echo 'Logout';?></a></li>
            </ul>
           
        </div>
    <header>
        <div id="logo">
            <a href="dashboard.html">Logo Here</a>
        </div>
    <section id='content'> <?php echo $this->layout()->content;?></section>
    <footer>Copyright by coderockr.com 2013</footer>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
<script src="/js/main.js"></script>
</body>
</html>